version: '2'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
    - 4444:4444/udp
    - 8086:8086
    environment:
    - INFLUXDB_DB=brewmon
    volumes:
    - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    #- /data/influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    links:
    - influxdb
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
    - ./grafana/provisioning/:/etc/grafana/provisioning/
    #- /data/grafana:/var/lib/grafana
