{
 "title": "BrewMon Template",
 "description": "BrewPi and iSpindel metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "2m",
 "templating": {
  "list": [
   { "name": "beer_name", "label": "Beer", "query": "show series" }
  ]
 },
 "panels": [
  {
   "title": "Beer",
   "type": "singlestat",
   "description": "Current Wort temperature",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "measurement": "/^$beer_name$/",
     "select": [
      [
       { "params": [ "beer_temp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Beer Setting",
   "type": "singlestat",
   "description": "The target temperature for the Wort",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "measurement": "/^$beer_name$/",
     "select": [
      [
       { "params": [ "beer_setting_temp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "The current gap between beer and beer setting",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "measurement": "/^$beer_name$/",
     "query": "SELECT abs(\"beer_temp\" - \"beer_setting_temp\") FROM /^$beer_name$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "beer_temp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fridge",
   "type": "singlestat",
   "description": "The current Fridge temperature",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "measurement": "/^$beer_name$/",
     "select": [
      [
       { "params": [ "fridge_temp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fridge Setting",
   "type": "singlestat",
   "description": "The target Fridge temperature driven by BrewPi",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "measurement": "/^$beer_name$/",
     "select": [
      [
       { "params": [ "fridge_setting_temp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "description": "The current gap between fridge and fridge setting",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "measurement": "/^$beer_name$/",
     "query": "SELECT abs(\"fridge_temp\" - \"fridge_setting_temp\") FROM /^$beer_name$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "beer_temp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gravity",
   "type": "singlestat",
   "description": "Current gravity in Plato",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "format": "degree",
   "valueName": "current",
   "targets": [
    {
     "measurement": "measurements",
     "select": [
      [
       { "params": [ "gravity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "iSpindel Bat.",
   "type": "singlestat",
   "description": "Battery",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "measurement": "measurements",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "description": "Temperatures from BrewPi",
   "gridPos": { "h": 15, "w": 18, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "/^$beer_name$/",
     "query": "SELECT \"state_cooling\" AS \"Cooling\", \"state_heating\" AS \"Heating\", \"room_temp\" AS \"Room\", \"fridge_setting_temp\" AS \"Fridge Setting\", \"fridge_temp\" AS \"Fridge\", \"beer_setting_temp\" AS \"Beer Setting\", \"beer_temp\" AS \"Beer\" FROM /^$beer_name$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "beer_temp" ], "type": "field" },
       { "params": [ "Beer" ], "type": "alias" }
      ],
      [
       { "params": [ "fridge_temp" ], "type": "field" },
       { "params": [ "Fridge" ], "type": "alias" }
      ],
      [
       { "params": [ "state_cooling" ], "type": "field" },
       { "params": [ "Cooling" ], "type": "alias" }
      ],
      [
       { "params": [ "state_heating" ], "type": "field" },
       { "params": [ "Heating" ], "type": "alias" }
      ],
      [
       { "params": [ "room_temp" ], "type": "field" },
       { "params": [ "Room" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "measurement": "measurements",
     "query": "SELECT \"gravity\" AS \"Gravity\" FROM \"measurements\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "gravity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "iSpindel",
   "type": "graph",
   "description": "Gravity and temperature from iSpindel",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "measurements",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       { "params": [ "Temp" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "measurement": "measurements",
     "select": [
      [
       { "params": [ "gravity" ], "type": "field" },
       { "params": [ "Gravity" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Annotations",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}